#ifndef __TZUTE_LIMITS_H
#define __TZUTE_LIMITS_H

#define VARCHAR_MAX_LEN		1024
#define VARCHAR_MAX_SIZE	(VARCHAR_MAX_LEN + 1)
#define	CHAR_MAX_LEN		8
#define CHAR_MAX_SIZE		(CHAR_MAX_LEN + 1)
#define CSV_HEADER_MAX		20

#endif
